POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "username": "uyencao",
    "password": "0909876987",
    "role": "customer",
    "name": "uyen cao",
    "address": "XYZ street"
}

###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "username": "uyencaobusiness",
    "password": "123123123",
    "role": "vendor",
    "businessName": "uyen cao business",
    "businessAddress": "Business street"
}

###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "username": "uyencaoshipper",
    "password": "123123123",
    "role": "shipper",
    "hub": "644d5bec0c7cd5f48a9eee74"
}

###
POST http://localhost:3001/api/hub
Content-Type: application/json

{
    "name": "DECA Hub",
    "address": "DECA Street"
}