POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "username": "uyencao",
    "password": "123123",
    "role": "customer",
    "name": "uyen cao",
    "address": "XYZ street"
}

###
POST https://smoky-mini-lazada-be.onrender.com/api/auth/register
Content-Type: application/json

{
    "username": "uyencaowithrender",
    "password": "123123",
    "role": "customer",
    "name": "uyen cao with render",
    "address": "RENDER street"
}

###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "username": "uyencaobusiness",
    "password": "123123123",
    "role": "vendor",
    "businessName": "uyen cao business",
    "businessAddress": "Business street"
}

###
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "username": "uyencaoshipper",
    "password": "123123123",
    "role": "shipper",
    "hub": "644d5bec0c7cd5f48a9eee74"
}

###
POST http://localhost:3001/api/hub
Content-Type: application/json

{
    "name": "DECA Hub",
    "address": "DECA Street"
}

###

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "username": "uyencao",
    "password": "123123"
}


###

POST http://localhost:3001/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoidXllbmNhb2J1c2luZXNzIiwicm9sZSI6InZlbmRvciJ9LCJpYXQiOjE2ODI4NDY2MTcsImV4cCI6MTY4Mjg4MjYxN30.4dyzjVKMShZGEUonm9E487bWWzsg5AjWvJGCWyBN54A

{
    "name": "product 1",
    "price": 21,
    "description": "a good product",
    "image": "",
    "vendor": "644d57fe01305b12227fba09"
}